// Code generated by "stringer -type=Opcode -trimprefix=Op"; DO NOT EDIT.

package isa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpLW-0]
	_ = x[OpSW-1]
	_ = x[OpLUI-2]
	_ = x[OpJZ-3]
	_ = x[OpMV-4]
	_ = x[OpINV-5]
	_ = x[OpADDI-6]
	_ = x[OpADD-7]
	_ = x[OpSUB-8]
	_ = x[OpMUL-9]
	_ = x[OpAND-10]
	_ = x[OpJ-11]
	_ = x[OpJR-12]
	_ = x[OpHALT-13]
	_ = x[OpDIV-14]
	_ = x[OpMOD-15]
	_ = x[OpJG-16]
	_ = x[OpJL-17]
}

const _Opcode_name = "LWSWLUIJZMVINVADDIADDSUBMULANDJJRHALTDIVMODJGJL"

var _Opcode_index = [...]uint8{0, 2, 4, 7, 9, 11, 14, 18, 21, 24, 27, 30, 31, 33, 37, 40, 43, 45, 47}

func (i Opcode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Opcode_index)-1 {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[idx]:_Opcode_index[idx+1]]
}
