// Code generated by "stringer -type=Register"; DO NOT EDIT.

package isa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SP-0]
	_ = x[RP-1]
	_ = x[X0-2]
	_ = x[X1-3]
	_ = x[X2-4]
	_ = x[X3-5]
	_ = x[X4-6]
	_ = x[T0-7]
	_ = x[T1-8]
	_ = x[T2-9]
	_ = x[T3-10]
	_ = x[T4-11]
	_ = x[A0-12]
	_ = x[A1-13]
	_ = x[A2-14]
	_ = x[ZERO-15]
}

const _Register_name = "SPRPX0X1X2X3X4T0T1T2T3T4A0A1A2ZERO"

var _Register_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 34}

func (i Register) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Register_index)-1 {
		return "Register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Register_name[_Register_index[idx]:_Register_index[idx+1]]
}
